"""add video s3_key

Revision ID: b5af3fa12a68
Revises: bbc54970ce58
Create Date: 2026-03-23 18:19:29.261991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5af3fa12a68'
down_revision: Union[str, Sequence[str], None] = 'bbc54970ce58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.add_column('video', sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('video', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'video', ['yoga_course_id', 'title'])
    op.create_unique_constraint(None, 'video', ['s3_key'])
    op.drop_column('video', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_column('video', 'is_active')
    op.drop_column('video', 'duration_seconds')
    op.drop_column('video', 's3_key')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    # ### end Alembic commands ###
