"""Changed GroupTrainings

Revision ID: bbc54970ce58
Revises: adef0a2e14bd
Create Date: 2026-03-16 13:13:48.060012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bbc54970ce58"
down_revision: Union[str, Sequence[str], None] = "adef0a2e14bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usertrip",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trip.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "trip_id"),
    )
    op.add_column(
        "grouptrainingstudio", sa.Column("training_date", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "grouptrainingstudio",
        sa.Column("training_info_id", sa.Integer(), nullable=False),
    )
    op.alter_column(
        "grouptrainingstudio", "studio_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_unique_constraint(
        None, "grouptrainingstudio", ["training_info_id", "studio_id"]
    )
    op.drop_constraint(
        op.f("grouptrainingstudio_studio_id_fkey"),
        "grouptrainingstudio",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "grouptrainingstudio",
        "grouptraininginfo",
        ["training_info_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "grouptrainingstudio",
        "studio",
        ["studio_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("grouptrainingstudio", "date")
    op.create_foreign_key(
        None,
        "grouptrainingstudiouser",
        "grouptrainingstudio",
        ["group_training_studio_id"],
        ["id"],
    )
    op.drop_column("grouptrainingstudiouser", "id")
    op.alter_column("trip", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "trip",
        "start_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "trip",
        "end_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_trip_location"), "trip", ["location"], unique=False)
    op.create_index(op.f("ix_trip_name"), "trip", ["name"], unique=False)
    op.drop_column("useryogacourse", "id")
    op.alter_column(
        "yogacourse", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "yogacourse", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.add_column(
        "useryogacourse",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_index(op.f("ix_trip_name"), table_name="trip")
    op.drop_index(op.f("ix_trip_location"), table_name="trip")
    op.alter_column(
        "trip",
        "end_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "trip",
        "start_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column("trip", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column(
        "grouptrainingstudiouser",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_constraint(None, "grouptrainingstudiouser", type_="foreignkey")
    op.add_column(
        "grouptrainingstudio",
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "grouptrainingstudio", type_="foreignkey")
    op.drop_constraint(None, "grouptrainingstudio", type_="foreignkey")
    op.create_foreign_key(
        op.f("grouptrainingstudio_studio_id_fkey"),
        "grouptrainingstudio",
        "studio",
        ["studio_id"],
        ["id"],
    )
    op.drop_constraint(None, "grouptrainingstudio", type_="unique")
    op.alter_column(
        "grouptrainingstudio", "studio_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("grouptrainingstudio", "training_info_id")
    op.drop_column("grouptrainingstudio", "training_date")
    op.drop_table("usertrip")
    # ### end Alembic commands ###
